# This is a basic workflow to help you get started with Actions

name: Make Random

# Controls when the action will run. 
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: install C++ compiler
        run: sudo apt install build-essential

      # Runs a set of commands using the runners shell
      - name: compile sources
        run: |
          g++ -std=c++11 random.cxx -o random.out
          g++ -std=c++11 tag.cxx -o tag.out
          
      - name: get random
        run: ./random.out
      
      - name: commit random
        run: |
          git add .
          git config --local user.email "szdytom@163.com"
          git config --local user.name "szdytom"
          git commit -sm "[auto] update random"
      
      - name: set tag
        run: ./tag.out
      
      - name: commit counter
        run: |
          git add .
          git commit -sm "[auto] update counter"
      
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
